# Complete games data for all 29 games
# Each game has 15 questions, each worth 2 points (total 30 points)
# Pass mark: 15 points (50%)

GAMES_DATA = [
    {
        "id": 1,
        "name": "Math Marathon → Fruit Shop Math Sprint",
        "description": "Test your math processing speed with fruit shop calculations",
        "questions": [
            {"question": "2 + 1 = ?", "options": ["2", "3", "4", "5"], "correct": "3", "points": 2},
            {"question": "5 - 2 = ?", "options": ["1", "2", "3", "4"], "correct": "3", "points": 2},
            {"question": "4 + 3 = ?", "options": ["5", "6", "7", "8"], "correct": "7", "points": 2},
            {"question": "6 - 1 = ?", "options": ["4", "5", "6", "7"], "correct": "5", "points": 2},
            {"question": "1 + 4 = ?", "options": ["4", "5", "6", "7"], "correct": "5", "points": 2},
            {"question": "8 - 3 = ?", "options": ["4", "5", "6", "7"], "correct": "5", "points": 2},
            {"question": "2 + 2 = ?", "options": ["2", "3", "4", "5"], "correct": "4", "points": 2},
            {"question": "7 - 2 = ?", "options": ["4", "5", "6", "7"], "correct": "5", "points": 2},
            {"question": "3 + 3 = ?", "options": ["5", "6", "7", "8"], "correct": "6", "points": 2},
            {"question": "9 - 4 = ?", "options": ["4", "5", "6", "7"], "correct": "5", "points": 2},
            {"question": "0 + 5 = ?", "options": ["0", "5", "10", "15"], "correct": "5", "points": 2},
            {"question": "6 - 4 = ?", "options": ["1", "2", "3", "4"], "correct": "2", "points": 2},
            {"question": "4 + 4 = ?", "options": ["6", "7", "8", "9"], "correct": "8", "points": 2},
            {"question": "10 - 3 = ?", "options": ["5", "6", "7", "8"], "correct": "7", "points": 2},
            {"question": "2 + 7 = ?", "options": ["8", "9", "10", "11"], "correct": "9", "points": 2},
        ]
    },
    {
        "id": 2,
        "name": "Pattern Puzzler → Crack the Colour Code",
        "description": "Complete the pattern sequences",
        "questions": [
            {"question": "Red, Blue, Red, Blue, ?", "options": ["Red", "Blue", "Green", "Yellow"], "correct": "Red", "points": 2},
            {"question": "Star, Star, Circle, Star, Star, ?", "options": ["Star", "Circle", "Square", "Triangle"], "correct": "Circle", "points": 2},
            {"question": "Big, small, big, small, ?", "options": ["Big", "Small", "Medium", "Tiny"], "correct": "Big", "points": 2},
            {"question": "Up, up, down, up, up, ?", "options": ["Up", "Down", "Left", "Right"], "correct": "Down", "points": 2},
            {"question": "A, B, C, A, B, ?", "options": ["A", "B", "C", "D"], "correct": "C", "points": 2},
            {"question": "Square, triangle, square, triangle, ?", "options": ["Square", "Triangle", "Circle", "Rectangle"], "correct": "Square", "points": 2},
            {"question": "Cat, dog, bird, cat, dog, ?", "options": ["Cat", "Dog", "Bird", "Fish"], "correct": "Bird", "points": 2},
            {"question": "1, 1, 2, 1, 1, ?", "options": ["1", "2", "3", "4"], "correct": "2", "points": 2},
            {"question": "Clap, stomp, clap, stomp, ?", "options": ["Clap", "Stomp", "Wave", "Jump"], "correct": "Clap", "points": 2},
            {"question": "Red, red, yellow, red, red, ?", "options": ["Red", "Yellow", "Blue", "Green"], "correct": "Yellow", "points": 2},
            {"question": "Happy, sad, happy, sad, ?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Happy", "points": 2},
            {"question": "Circle, square, triangle, circle, ?", "options": ["Circle", "Square", "Triangle", "Rectangle"], "correct": "Square", "points": 2},
            {"question": "Day, night, day, night, ?", "options": ["Day", "Night", "Morning", "Evening"], "correct": "Day", "points": 2},
            {"question": "Apple, apple, banana, apple, apple, ?", "options": ["Apple", "Banana", "Orange", "Grape"], "correct": "Banana", "points": 2},
            {"question": "High, low, medium, high, low, ?", "options": ["High", "Low", "Medium", "Very High"], "correct": "Medium", "points": 2},
        ]
    },
    {
        "id": 3,
        "name": "Memory Match → Memory Zoo",
        "description": "Test your working memory with zoo animals (Animals shown: Elephant, Giraffe, Monkey, Lion)",
        "questions": [
            {"question": "First animal shown was Elephant. Which animal was first?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Elephant", "points": 2},
            {"question": "Second animal: Giraffe. Which came second?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Giraffe", "points": 2},
            {"question": "Third animal: Monkey. Which came third?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Monkey", "points": 2},
            {"question": "Fourth animal: Lion. Which came fourth?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Lion", "points": 2},
            {"question": "What was the first animal again?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Elephant", "points": 2},
            {"question": "What was the third animal again?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Monkey", "points": 2},
            {"question": "Was Zebra shown in the list?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "What was the second animal?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Giraffe", "points": 2},
            {"question": "Was Penguin shown?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "What was the fourth animal?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Lion", "points": 2},
            {"question": "Which two animals came first and third?", "options": ["Elephant & Monkey", "Giraffe & Lion", "Elephant & Giraffe", "Monkey & Lion"], "correct": "Elephant & Monkey", "points": 2},
            {"question": "Which two animals came second and fourth?", "options": ["Elephant & Monkey", "Giraffe & Lion", "Elephant & Giraffe", "Monkey & Lion"], "correct": "Giraffe & Lion", "points": 2},
            {"question": "Which animal came right after Elephant?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Giraffe", "points": 2},
            {"question": "Which animal came right before Lion?", "options": ["Elephant", "Giraffe", "Monkey", "Lion"], "correct": "Monkey", "points": 2},
            {"question": "How many animals were shown in total?", "options": ["2", "3", "4", "5"], "correct": "4", "points": 2},
        ]
    },
    {
        "id": 4,
        "name": "Word Builder → Monster Chef Letter Soup",
        "description": "Build words from sounds - phoneme awareness",
        "questions": [
            {"question": "/c/ /a/ /t/ makes which word?", "options": ["Cat", "Bat", "Rat", "Hat"], "correct": "Cat", "points": 2},
            {"question": "/d/ /o/ /g/ makes which word?", "options": ["Dog", "Fog", "Log", "Hog"], "correct": "Dog", "points": 2},
            {"question": "/s/ /u/ /n/ makes which word?", "options": ["Sun", "Run", "Fun", "Bun"], "correct": "Sun", "points": 2},
            {"question": "/f/ /i/ /sh/ makes which word?", "options": ["Fish", "Dish", "Wish", "Swish"], "correct": "Fish", "points": 2},
            {"question": "/b/ /e/ /d/ makes which word?", "options": ["Bed", "Red", "Led", "Fed"], "correct": "Bed", "points": 2},
            {"question": "/p/ /i/ /g/ makes which word?", "options": ["Pig", "Big", "Wig", "Dig"], "correct": "Pig", "points": 2},
            {"question": "/m/ /a/ /n/ makes which word?", "options": ["Man", "Fan", "Pan", "Can"], "correct": "Man", "points": 2},
            {"question": "/r/ /a/ /t/ makes which word?", "options": ["Rat", "Bat", "Cat", "Hat"], "correct": "Rat", "points": 2},
            {"question": "/l/ /e/ /g/ makes which word?", "options": ["Leg", "Beg", "Peg", "Meg"], "correct": "Leg", "points": 2},
            {"question": "/h/ /a/ /t/ makes which word?", "options": ["Hat", "Bat", "Cat", "Rat"], "correct": "Hat", "points": 2},
            {"question": "/c/ /u/ /p/ makes which word?", "options": ["Cup", "Pup", "Up", "Sup"], "correct": "Cup", "points": 2},
            {"question": "/b/ /u/ /s/ makes which word?", "options": ["Bus", "Us", "Muss", "Plus"], "correct": "Bus", "points": 2},
            {"question": "/f/ /o/ /x/ makes which word?", "options": ["Fox", "Box", "Ox", "Pox"], "correct": "Fox", "points": 2},
            {"question": "/w/ /e/ /b/ makes which word?", "options": ["Web", "Deb", "Beb", "Zeb"], "correct": "Web", "points": 2},
            {"question": "/n/ /e/ /t/ makes which word?", "options": ["Net", "Pet", "Set", "Get"], "correct": "Net", "points": 2},
        ]
    },
    {
        "id": 5,
        "name": "Story Sequence → Picture Order",
        "description": "What happens next? Complete the story sequence",
        "questions": [
            {"question": "You wake up. Then you brush your teeth. What happens NEXT?", "options": ["Eat breakfast", "Go to sleep", "Take a shower", "Watch TV"], "correct": "Eat breakfast", "points": 2},
            {"question": "Plant a seed. Water it. What happens NEXT?", "options": ["It grows", "It dies", "It flies away", "It stays the same"], "correct": "It grows", "points": 2},
            {"question": "Put on shoes. Tie them. What happens NEXT?", "options": ["Walk", "Take them off", "Sleep", "Eat"], "correct": "Walk", "points": 2},
            {"question": "Draw a circle. Draw eyes inside. What happens NEXT?", "options": ["Draw a mouth", "Erase it", "Color it blue", "Cut it out"], "correct": "Draw a mouth", "points": 2},
            {"question": "Egg cracks open. Chick comes out. What happens NEXT?", "options": ["Chick walks", "Egg reforms", "Chick sleeps", "Chick flies"], "correct": "Chick walks", "points": 2},
            {"question": "Rain falls. Puddles form. What happens NEXT?", "options": ["Splash", "Sun comes out", "Snow falls", "Wind blows"], "correct": "Splash", "points": 2},
            {"question": "Cut paper. Fold it. What happens NEXT?", "options": ["Make a card", "Throw it away", "Color it", "Burn it"], "correct": "Make a card", "points": 2},
            {"question": "Mix flour and eggs. Bake it. What happens NEXT?", "options": ["Eat cake", "Add more flour", "Freeze it", "Throw it out"], "correct": "Eat cake", "points": 2},
            {"question": "Dog wags tail. Sees leash. What happens NEXT?", "options": ["Go for walk", "Run away", "Hide", "Sleep"], "correct": "Go for walk", "points": 2},
            {"question": "Turn on tap. Wet hands. What happens NEXT?", "options": ["Add soap", "Dry hands", "Turn off tap", "Leave"], "correct": "Add soap", "points": 2},
            {"question": "Open book. Read page 1. What happens NEXT?", "options": ["Read page 2", "Close book", "Throw book", "Sleep"], "correct": "Read page 2", "points": 2},
            {"question": "Build tower. Add blocks. What happens NEXT?", "options": ["Tower gets taller", "Tower falls", "Stop building", "Color it"], "correct": "Tower gets taller", "points": 2},
            {"question": "Butterfly egg. Caterpillar. What happens NEXT?", "options": ["Cocoon", "Butterfly", "Die", "Fly away"], "correct": "Cocoon", "points": 2},
            {"question": "Push swing. Sit on it. What happens NEXT?", "options": ["Swing moves", "Stop", "Get off", "Sleep"], "correct": "Swing moves", "points": 2},
            {"question": "Get mail. Open envelope. What happens NEXT?", "options": ["Read letter", "Throw away", "Save it", "Hide it"], "correct": "Read letter", "points": 2},
        ]
    },
    {
        "id": 6,
        "name": "Colour Catch → Rainbow Robot Says",
        "description": "Follow the color instructions - pay attention to spoken instruction vs written word",
        "questions": [
            {"question": "Robot says 'Touch RED'. Word shows BLUE. What color should you touch?", "options": ["RED", "BLUE", "GREEN", "YELLOW"], "correct": "RED", "points": 2},
            {"question": "Robot says 'Touch YELLOW'. Word shows YELLOW. What color should you touch?", "options": ["RED", "BLUE", "GREEN", "YELLOW"], "correct": "YELLOW", "points": 2},
            {"question": "Robot says 'Touch BLUE'. Word shows RED. What color should you touch?", "options": ["RED", "BLUE", "GREEN", "YELLOW"], "correct": "BLUE", "points": 2},
            {"question": "Robot says 'Touch GREEN'. Word shows GREEN. What color should you touch?", "options": ["RED", "BLUE", "GREEN", "YELLOW"], "correct": "GREEN", "points": 2},
            {"question": "Robot says 'Touch ORANGE'. Word shows PURPLE. What color should you touch?", "options": ["ORANGE", "PURPLE", "RED", "BLUE"], "correct": "ORANGE", "points": 2},
            {"question": "Robot says 'Touch PINK'. Word shows PINK. What color should you touch?", "options": ["PINK", "RED", "BLUE", "GREEN"], "correct": "PINK", "points": 2},
            {"question": "Robot says 'Touch BROWN'. Word shows BLACK. What color should you touch?", "options": ["BROWN", "BLACK", "WHITE", "GREY"], "correct": "BROWN", "points": 2},
            {"question": "Robot says 'Touch BLACK'. Word shows BROWN. What color should you touch?", "options": ["BROWN", "BLACK", "WHITE", "GREY"], "correct": "BLACK", "points": 2},
            {"question": "Robot says 'Touch PURPLE'. Word shows PURPLE. What color should you touch?", "options": ["RED", "BLUE", "PURPLE", "GREEN"], "correct": "PURPLE", "points": 2},
            {"question": "Robot says 'Touch GREY'. Word shows GREY. What color should you touch?", "options": ["GREY", "BLACK", "WHITE", "BROWN"], "correct": "GREY", "points": 2},
            {"question": "Robot says 'Touch WHITE'. Word shows BLACK. What color should you touch?", "options": ["WHITE", "BLACK", "GREY", "BROWN"], "correct": "WHITE", "points": 2},
            {"question": "Robot says 'Touch RED'. Word shows RED. What color should you touch?", "options": ["RED", "BLUE", "GREEN", "YELLOW"], "correct": "RED", "points": 2},
            {"question": "Robot says 'Touch BLUE'. Word shows BLUE. What color should you touch?", "options": ["RED", "BLUE", "GREEN", "YELLOW"], "correct": "BLUE", "points": 2},
            {"question": "Robot says 'Touch GREEN'. Word shows RED. What color should you touch?", "options": ["RED", "BLUE", "GREEN", "YELLOW"], "correct": "GREEN", "points": 2},
            {"question": "Robot says 'Touch YELLOW'. Word shows BLUE. What color should you touch?", "options": ["RED", "BLUE", "GREEN", "YELLOW"], "correct": "YELLOW", "points": 2},
        ]
    },
    {
        "id": 7,
        "name": "Number Ninja → Number Slice",
        "description": "Slice only the target number - test your number processing speed",
        "questions": [
            {"question": "Target: 5. Slice 5?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Target: 5. Slice 2?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Target: 5. Slice 5?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Target: 5. Slice 8?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Target: 5. Slice 5?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Target: Even numbers. Slice 4?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Target: Even numbers. Slice 7?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Target: Even numbers. Slice 10?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Target: Even numbers. Slice 3?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Target: Even numbers. Slice 6?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Target: Numbers bigger than 6. Slice 8?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Target: Numbers bigger than 6. Slice 5?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Target: Numbers bigger than 6. Slice 9?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Target: Numbers bigger than 6. Slice 4?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Target: Numbers bigger than 6. Slice 7?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 8,
        "name": "Follow the Leader → Monkey Dance School",
        "description": "Remember and repeat the sequence of actions",
        "questions": [
            {"question": "Sequence: Tap head, clap. What did Monkey do FIRST?", "options": ["Tap head", "Clap", "Stomp", "Jump"], "correct": "Tap head", "points": 2},
            {"question": "Sequence: Jump, turn around. What did Monkey do FIRST?", "options": ["Jump", "Turn around", "Clap", "Nod"], "correct": "Jump", "points": 2},
            {"question": "Sequence: Clap, stomp, nod. What was the SECOND action?", "options": ["Clap", "Stomp", "Nod", "Jump"], "correct": "Stomp", "points": 2},
            {"question": "Sequence: Wave, tap knees. What was the SECOND action?", "options": ["Wave", "Tap knees", "Clap", "Nod"], "correct": "Tap knees", "points": 2},
            {"question": "Sequence: Nod, clap, jump. What was the THIRD action?", "options": ["Nod", "Clap", "Jump", "Wave"], "correct": "Jump", "points": 2},
            {"question": "Sequence: Turn, wave. What did Monkey do FIRST?", "options": ["Turn", "Wave", "Clap", "Nod"], "correct": "Turn", "points": 2},
            {"question": "Sequence: Stomp, clap, nod. What was the SECOND action?", "options": ["Stomp", "Clap", "Nod", "Wave"], "correct": "Clap", "points": 2},
            {"question": "Sequence: Tap head, jump, turn. What was the THIRD action?", "options": ["Tap head", "Jump", "Turn", "Clap"], "correct": "Turn", "points": 2},
            {"question": "Sequence: Clap, wave. What did Monkey do FIRST?", "options": ["Clap", "Wave", "Stomp", "Nod"], "correct": "Clap", "points": 2},
            {"question": "Sequence: Nod, stomp. What was the SECOND action?", "options": ["Nod", "Stomp", "Clap", "Jump"], "correct": "Stomp", "points": 2},
            {"question": "Sequence: Jump, tap head, clap. What did Monkey do FIRST?", "options": ["Jump", "Tap head", "Clap", "Wave"], "correct": "Jump", "points": 2},
            {"question": "Sequence: Turn, nod, wave. What was the SECOND action?", "options": ["Turn", "Nod", "Wave", "Clap"], "correct": "Nod", "points": 2},
            {"question": "Sequence: Tap knees, jump. What was the SECOND action?", "options": ["Tap knees", "Jump", "Clap", "Turn"], "correct": "Jump", "points": 2},
            {"question": "Sequence: Clap, tap head, stomp. What was the THIRD action?", "options": ["Clap", "Tap head", "Stomp", "Wave"], "correct": "Stomp", "points": 2},
            {"question": "Sequence: Wave, nod, turn. What did Monkey do FIRST?", "options": ["Wave", "Nod", "Turn", "Clap"], "correct": "Wave", "points": 2},
        ]
    },
    {
        "id": 9,
        "name": "Rhyme Time → Find the Rhyme",
        "description": "Find the word that rhymes with the given word",
        "questions": [
            {"question": "Which word rhymes with Cat?", "options": ["Hat", "Dog", "Sun", "Fish"], "correct": "Hat", "points": 2},
            {"question": "Which word rhymes with Dog?", "options": ["Log", "Cat", "Bird", "Fish"], "correct": "Log", "points": 2},
            {"question": "Which word rhymes with Sun?", "options": ["Bun", "Dog", "Cat", "Fish"], "correct": "Bun", "points": 2},
            {"question": "Which word rhymes with Fish?", "options": ["Dish", "Dog", "Cat", "Sun"], "correct": "Dish", "points": 2},
            {"question": "Which word rhymes with Bed?", "options": ["Red", "Dog", "Cat", "Fish"], "correct": "Red", "points": 2},
            {"question": "Which word rhymes with Pig?", "options": ["Wig", "Dog", "Cat", "Sun"], "correct": "Wig", "points": 2},
            {"question": "Which word rhymes with Man?", "options": ["Fan", "Dog", "Cat", "Fish"], "correct": "Fan", "points": 2},
            {"question": "Which word rhymes with Rat?", "options": ["Bat", "Dog", "Sun", "Fish"], "correct": "Bat", "points": 2},
            {"question": "Which word rhymes with Leg?", "options": ["Egg", "Dog", "Cat", "Fish"], "correct": "Egg", "points": 2},
            {"question": "Which word rhymes with Cup?", "options": ["Pup", "Dog", "Cat", "Sun"], "correct": "Pup", "points": 2},
            {"question": "Which word rhymes with Bus?", "options": ["Gus", "Dog", "Cat", "Fish"], "correct": "Gus", "points": 2},
            {"question": "Which word rhymes with Fox?", "options": ["Box", "Dog", "Cat", "Sun"], "correct": "Box", "points": 2},
            {"question": "Which word rhymes with Web?", "options": ["Deb", "Dog", "Cat", "Fish"], "correct": "Deb", "points": 2},
            {"question": "Which word rhymes with Net?", "options": ["Vet", "Dog", "Cat", "Sun"], "correct": "Vet", "points": 2},
            {"question": "Which word rhymes with Car?", "options": ["Star", "Dog", "Cat", "Fish"], "correct": "Star", "points": 2},
        ]
    },
    {
        "id": 10,
        "name": "Treasure Hunt → Working Memory Map",
        "description": "Remember where the treasure is hidden among Red, Blue, Yellow boxes",
        "questions": [
            {"question": "Treasure hidden in Red box. Where is the treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Red", "points": 2},
            {"question": "Treasure hidden in Blue box. Where is the treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Blue", "points": 2},
            {"question": "Treasure hidden in Yellow box. Where is the treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Yellow", "points": 2},
            {"question": "Treasure hidden in Red box. Where is the treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Red", "points": 2},
            {"question": "Treasure hidden in Blue box. Where is the treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Blue", "points": 2},
            {"question": "Treasure hidden in Yellow box. Where is the treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Yellow", "points": 2},
            {"question": "Treasure hidden in Red box. Was it Blue box?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Treasure hidden in Blue box. Was it Yellow box?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Treasure hidden in Yellow box. Was it Red box?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Treasure hidden in Red box. Name all three colors.", "options": ["Red, Blue, Yellow", "Red, Green, Blue", "Blue, Yellow, Green", "Red, Yellow, Green"], "correct": "Red, Blue, Yellow", "points": 2},
            {"question": "Treasure hidden in Blue box. Name all three colors.", "options": ["Red, Blue, Yellow", "Red, Green, Blue", "Blue, Yellow, Green", "Red, Yellow, Green"], "correct": "Red, Blue, Yellow", "points": 2},
            {"question": "Treasure hidden in Yellow box. Which colors were NOT used?", "options": ["Red and Blue", "Blue and Yellow", "Red and Yellow", "Only Green"], "correct": "Red and Blue", "points": 2},
            {"question": "Treasure hidden in Red box. Which color had treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Red", "points": 2},
            {"question": "Treasure hidden in Blue box. Which color had treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Blue", "points": 2},
            {"question": "Treasure hidden in Yellow box. Which color had treasure?", "options": ["Red", "Blue", "Yellow", "Green"], "correct": "Yellow", "points": 2},
        ]
    },
    {
        "id": 11,
        "name": "Clock Master → What Time Is It?",
        "description": "Tell the time on analog and digital clocks",
        "questions": [
            {"question": "What time is 3:00?", "options": ["3 o'clock", "6 o'clock", "9 o'clock", "12 o'clock"], "correct": "3 o'clock", "points": 2},
            {"question": "What time is 6:00?", "options": ["3 o'clock", "6 o'clock", "9 o'clock", "12 o'clock"], "correct": "6 o'clock", "points": 2},
            {"question": "What time is 9:00?", "options": ["3 o'clock", "6 o'clock", "9 o'clock", "12 o'clock"], "correct": "9 o'clock", "points": 2},
            {"question": "What time is 12:00?", "options": ["3 o'clock", "6 o'clock", "9 o'clock", "12 o'clock"], "correct": "12 o'clock", "points": 2},
            {"question": "What time is 1:00?", "options": ["1 o'clock", "2 o'clock", "3 o'clock", "4 o'clock"], "correct": "1 o'clock", "points": 2},
            {"question": "What time is 4:30?", "options": ["Half past 4", "Half past 3", "Half past 5", "Half past 6"], "correct": "Half past 4", "points": 2},
            {"question": "What time is 7:30?", "options": ["Half past 7", "Half past 6", "Half past 8", "Half past 5"], "correct": "Half past 7", "points": 2},
            {"question": "What time is 10:30?", "options": ["Half past 10", "Half past 9", "Half past 11", "Half past 8"], "correct": "Half past 10", "points": 2},
            {"question": "What time is 2:30?", "options": ["Half past 2", "Half past 1", "Half past 3", "Half past 4"], "correct": "Half past 2", "points": 2},
            {"question": "You wake up at 7:00 in the morning. What time is that?", "options": ["7 o'clock", "8 o'clock", "6 o'clock", "5 o'clock"], "correct": "7 o'clock", "points": 2},
            {"question": "Lunch time is 12:00. What time is that?", "options": ["12 o'clock", "1 o'clock", "11 o'clock", "2 o'clock"], "correct": "12 o'clock", "points": 2},
            {"question": "Bedtime is 8:00. What time is that?", "options": ["8 o'clock", "7 o'clock", "9 o'clock", "10 o'clock"], "correct": "8 o'clock", "points": 2},
            {"question": "What time is half past 1?", "options": ["1:30", "1:00", "2:00", "12:30"], "correct": "1:30", "points": 2},
            {"question": "What time is half past 5?", "options": ["5:30", "5:00", "6:00", "4:30"], "correct": "5:30", "points": 2},
            {"question": "What time is half past 11?", "options": ["11:30", "11:00", "12:00", "10:30"], "correct": "11:30", "points": 2},
        ]
    },
    {
        "id": 12,
        "name": "Emotion Detective → How Does the Fox Feel?",
        "description": "Identify emotions from different situations",
        "questions": [
            {"question": "You get a present. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Happy", "points": 2},
            {"question": "Your toy breaks. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Sad", "points": 2},
            {"question": "Someone takes your turn. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Angry", "points": 2},
            {"question": "You see a big spider. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Scared", "points": 2},
            {"question": "You see a rainbow. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Happy", "points": 2},
            {"question": "Your friend moves away. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Sad", "points": 2},
            {"question": "You are pushed. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Angry", "points": 2},
            {"question": "A loud boom. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Scared", "points": 2},
            {"question": "You win a game. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Happy", "points": 2},
            {"question": "No one plays with you. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Sad", "points": 2},
            {"question": "Someone hides your pencil. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Angry", "points": 2},
            {"question": "Dark room alone. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Scared", "points": 2},
            {"question": "You get a hug. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Happy", "points": 2},
            {"question": "You lose your pet. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Sad", "points": 2},
            {"question": "Someone breaks your drawing. How do you feel?", "options": ["Happy", "Sad", "Angry", "Scared"], "correct": "Angry", "points": 2},
        ]
    },
    {
        "id": 13,
        "name": "Sorting Station → Tidy Up Game",
        "description": "Categorize items into correct groups",
        "questions": [
            {"question": "Apple belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Fruit", "points": 2},
            {"question": "Carrot belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Vegetable", "points": 2},
            {"question": "Lion belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Zoo animal", "points": 2},
            {"question": "Sofa belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Furniture", "points": 2},
            {"question": "Shirt belongs to which group?", "options": ["Clothes", "Fruit", "Vegetable", "Furniture"], "correct": "Clothes", "points": 2},
            {"question": "Banana belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Fruit", "points": 2},
            {"question": "Broccoli belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Vegetable", "points": 2},
            {"question": "Penguin belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Zoo animal", "points": 2},
            {"question": "Table belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Furniture", "points": 2},
            {"question": "Socks belong to which group?", "options": ["Clothes", "Fruit", "Vegetable", "Furniture"], "correct": "Clothes", "points": 2},
            {"question": "Orange belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Fruit", "points": 2},
            {"question": "Potato belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Vegetable", "points": 2},
            {"question": "Bear belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Zoo animal", "points": 2},
            {"question": "Bed belongs to which group?", "options": ["Fruit", "Vegetable", "Zoo animal", "Furniture"], "correct": "Furniture", "points": 2},
            {"question": "Hat belongs to which group?", "options": ["Clothes", "Fruit", "Vegetable", "Furniture"], "correct": "Clothes", "points": 2},
        ]
    },
    {
        "id": 14,
        "name": "Simon Says Challenge → Penguin Says",
        "description": "Only follow instructions that start with 'Penguin says' - test your impulse control",
        "questions": [
            {"question": "Penguin says touch nose. Should you do it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Jump (no Penguin says). Should you do it?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Penguin says clap. Should you do it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Sit down (no Penguin says). Should you do it?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Penguin says smile. Should you do it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Wave hand (no Penguin says). Should you do it?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Penguin says blink. Should you do it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Stand up (no Penguin says). Should you do it?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Penguin says look up. Should you do it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Laugh (no Penguin says). Should you do it?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Penguin says show teeth. Should you do it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Stomp feet (no Penguin says). Should you do it?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Penguin says raise hand. Should you do it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Turn around (no Penguin says). Should you do it?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Penguin says say 'hi'. Should you do it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 15,
        "name": "Continuous Performance Test → Space Signal Keeper",
        "description": "Tap only when you see a GREEN alien - test sustained attention",
        "questions": [
            {"question": "Green alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Purple alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Purple alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Blue alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Purple alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Orange alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Purple alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Pink alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green alien appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 16,
        "name": "Go/No-Go Animal Game → Feed the Right Animal",
        "description": "Tap for pig, no tap for wolf - test response inhibition",
        "questions": [
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Wolf appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Wolf appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Wolf appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Wolf appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Wolf appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Wolf appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Pig appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 17,
        "name": "Maze Runner → Find the Cheese",
        "description": "Navigate through the maze to find the cheese - test planning and persistence",
        "questions": [
            {"question": "Start at 1. Cheese at 3. What should you do?", "options": ["Forward 2 steps", "Backward 1 step", "Go left", "Go right"], "correct": "Forward 2 steps", "points": 2},
            {"question": "Left path leads to wall. Right path leads to cheese. Which path do you choose?", "options": ["Left", "Right", "Straight", "Back"], "correct": "Right", "points": 2},
            {"question": "Up has cheese. Down has trap. Which way do you go?", "options": ["Up", "Down", "Left", "Right"], "correct": "Up", "points": 2},
            {"question": "Mouse at bottom. Cheese top-left. What is your first move?", "options": ["Up then left", "Left then up", "Right then up", "Down then left"], "correct": "Up then left", "points": 2},
            {"question": "Two paths: long safe path, short scary path. Which do you choose?", "options": ["Long safe", "Short scary", "Both", "Neither"], "correct": "Long safe", "points": 2},
            {"question": "You reach a dead end. What should you do?", "options": ["Turn around", "Keep going", "Stop", "Go through wall"], "correct": "Turn around", "points": 2},
            {"question": "Cheese behind door. Need key first. What should you find?", "options": ["Key", "Cheese", "Door", "Window"], "correct": "Key", "points": 2},
            {"question": "Three turns to cheese. What is your first turn?", "options": ["Left", "Right", "Straight", "Back"], "correct": "Left", "points": 2},
            {"question": "You take a wrong turn. What should you do?", "options": ["Go back", "Keep going", "Give up", "Jump"], "correct": "Go back", "points": 2},
            {"question": "Cheese across bridge. Bridge is narrow. What should you do?", "options": ["Cross carefully", "Don't cross", "Run fast", "Jump over"], "correct": "Cross carefully", "points": 2},
            {"question": "One path has hole. Other path is clear. Which do you choose?", "options": ["Clear path", "Path with hole", "Both", "Neither"], "correct": "Clear path", "points": 2},
            {"question": "Cheese at end of straight line. Which way do you move?", "options": ["Straight", "Left", "Right", "Back"], "correct": "Straight", "points": 2},
            {"question": "Maze has arrow signs. Should you follow them?", "options": ["Yes", "No", "Maybe", "Never"], "correct": "Yes", "points": 2},
            {"question": "You see cheese but can't reach it yet. What is your next step?", "options": ["Find another way", "Give up", "Wait", "Shout"], "correct": "Find another way", "points": 2},
            {"question": "You've been trying for a long time. What should you do?", "options": ["Keep trying", "Give up", "Cry", "Break maze"], "correct": "Keep trying", "points": 2},
        ]
    },
    {
        "id": 18,
        "name": "Vigilance Watchtower → Lookout Keeper",
        "description": "Tap when you see a SHIP, not a bird - test sustained vigilance",
        "questions": [
            {"question": "Ship appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Bird appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Ship appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Bird appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Ship appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Bird appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Ship appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Bird appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Ship appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Ship appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Bird appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Ship appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Bird appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Ship appears. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Bird appears. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
        ]
    },
    {
        "id": 19,
        "name": "Stop Signal Reaction Game → Red Light, Green Light Race",
        "description": "Go on green (tap), stop on red (no tap) - test response cancellation",
        "questions": [
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Red light. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Red light. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Red light. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Red light. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Red light. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Red light. Should you tap?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Green light. Should you tap?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 20,
        "name": "Cookie Monster Delay → Wait for More",
        "description": "Choose between taking a small reward now or waiting for a larger reward - test delay of gratification",
        "questions": [
            {"question": "1 cookie now or 3 cookies later? Which do you choose?", "options": ["1 cookie now", "3 cookies later", "Both", "Neither"], "correct": "3 cookies later", "points": 2},
            {"question": "2 stickers now or 5 stickers later? Which do you choose?", "options": ["2 stickers now", "5 stickers later", "Both", "Neither"], "correct": "5 stickers later", "points": 2},
            {"question": "5 minutes play now or 10 minutes later? Which do you choose?", "options": ["5 min now", "10 min later", "Both", "Neither"], "correct": "10 min later", "points": 2},
            {"question": "Small candy now or big candy later? Which do you choose?", "options": ["Small candy now", "Big candy later", "Both", "Neither"], "correct": "Big candy later", "points": 2},
            {"question": "Short story now or long story later? Which do you choose?", "options": ["Short story now", "Long story later", "Both", "Neither"], "correct": "Long story later", "points": 2},
            {"question": "1 gold star now or 3 gold stars later? Which do you choose?", "options": ["1 star now", "3 stars later", "Both", "Neither"], "correct": "3 stars later", "points": 2},
            {"question": "Turn now or better turn later? Which do you choose?", "options": ["Turn now", "Better turn later", "Both", "Neither"], "correct": "Better turn later", "points": 2},
            {"question": "Small prize now or mystery prize later? Which do you choose?", "options": ["Small prize now", "Mystery later", "Both", "Neither"], "correct": "Mystery later", "points": 2},
            {"question": "One song now or two songs later? Which do you choose?", "options": ["One song now", "Two songs later", "Both", "Neither"], "correct": "Two songs later", "points": 2},
            {"question": "One high five now or three high fives later? Which do you choose?", "options": ["One now", "Three later", "Both", "Neither"], "correct": "Three later", "points": 2},
            {"question": "2 minutes tablet time now or 5 minutes later? Which do you choose?", "options": ["2 min now", "5 min later", "Both", "Neither"], "correct": "5 min later", "points": 2},
            {"question": "One toy now or two toys later? Which do you choose?", "options": ["One toy now", "Two toys later", "Both", "Neither"], "correct": "Two toys later", "points": 2},
            {"question": "Read one book now or two books later? Which do you choose?", "options": ["One book now", "Two books later", "Both", "Neither"], "correct": "Two books later", "points": 2},
            {"question": "One stamp now or four stamps later? Which do you choose?", "options": ["One stamp now", "Four stamps later", "Both", "Neither"], "correct": "Four stamps later", "points": 2},
            {"question": "Tickle now or tickle plus hug later? Which do you choose?", "options": ["Tickle now", "Tickle + hug later", "Both", "Neither"], "correct": "Tickle + hug later", "points": 2},
        ]
    },
    {
        "id": 21,
        "name": "N-Back Space Adventure (1-back)",
        "description": "Does the current item match the previous one? Test working memory",
        "questions": [
            {"question": "Sequence: Star, Moon. Does Moon match the previous (Star)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Moon, Moon. Does the second Moon match the previous?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Sequence: Moon, Star. Does Star match the previous (Moon)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Star, Planet. Does Planet match the previous (Star)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Planet, Planet. Does the second Planet match the previous?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Sequence: Planet, Star. Does Star match the previous (Planet)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Star, Star. Does the second Star match the previous?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Sequence: Star, Moon. Does Moon match the previous (Star)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Moon, Planet. Does Planet match the previous (Moon)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Planet, Planet. Does the second Planet match the previous?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Sequence: Planet, Moon. Does Moon match the previous (Planet)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Moon, Star. Does Star match the previous (Moon)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Star, Moon. Does Moon match the previous (Star)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Moon, Star. Does Star match the previous (Moon)?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Sequence: Star, Star. Does the second Star match the previous?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 22,
        "name": "Card Sort Challenge → Sort the Rules",
        "description": "Switch between sorting by shape and color - test cognitive flexibility",
        "questions": [
            {"question": "Rule: Sort by SHAPE. Red circle and Blue circle. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Rule: Sort by SHAPE. Red circle and Red square. Should they go together?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Rule: Sort by SHAPE. Blue triangle and Green triangle. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Rule: Sort by COLOR. Red circle and Red square. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Rule: Sort by COLOR. Blue triangle and Green triangle. Should they go together?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Rule: Sort by COLOR. Green square and Green circle. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Rule: Sort by SHAPE. Red circle and Blue circle. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Rule: Sort by COLOR. Red circle and Blue circle. Should they go together?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Rule: Sort by SHAPE. Red square and Blue square. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Rule: Sort by COLOR. Red square and Blue square. Should they go together?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Rule: Sort by SHAPE. Yellow triangle and Green triangle. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Rule: Sort by COLOR. Yellow triangle and Green triangle. Should they go together?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Rule: Sort by SHAPE. Blue star and Red star. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Rule: Sort by COLOR. Blue star and Red star. Should they go together?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Rule: Sort by COLOR. Green circle and Green square. Should they go together?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 23,
        "name": "Tower of Hanoi Quest → Move the Disks",
        "description": "Move all disks from left peg to right peg - test planning skills",
        "questions": [
            {"question": "Can a big disk go on top of a small disk?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Can a small disk go on top of a big disk?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You have 3 disks on Left peg. Goal is all disks on Right peg. What is the first move?", "options": ["Move small to Right", "Move small to Middle", "Move medium to Right", "Move big to Right"], "correct": "Move small to Right", "points": 2},
            {"question": "Small disk on Right. Medium disk on Left. Where can Medium disk go?", "options": ["Middle peg", "Right peg", "Left peg", "Anywhere"], "correct": "Middle peg", "points": 2},
            {"question": "Small disk is on top of Medium disk. Can you move the small disk?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You need to move the Large disk. What must happen first?", "options": ["Move small and medium", "Move only small", "Move only medium", "Move large directly"], "correct": "Move small and medium", "points": 2},
            {"question": "Can you move a disk if something is on top of it?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Can you move two disks at the same time?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Small on Middle. Medium on Left. Can Medium go to Middle?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "What is the best first move when starting with 3 disks?", "options": ["Small to Right", "Small to Middle", "Medium to Right", "Big to Middle"], "correct": "Small to Right", "points": 2},
            {"question": "After moving small to Right, what is the second move?", "options": ["Medium to Middle", "Small to Middle", "Medium to Right", "Big to Right"], "correct": "Medium to Middle", "points": 2},
            {"question": "Third move in solving 3-disk Tower of Hanoi?", "options": ["Small to Middle", "Medium to Right", "Small to Right", "Big to Middle"], "correct": "Small to Middle", "points": 2},
            {"question": "Fourth move in solving 3-disk Tower of Hanoi?", "options": ["Big to Right", "Small to Left", "Medium to Right", "Big to Middle"], "correct": "Big to Right", "points": 2},
            {"question": "Fifth move in solving 3-disk Tower of Hanoi?", "options": ["Small to Left", "Medium to Left", "Small to Right", "Big to Left"], "correct": "Small to Left", "points": 2},
            {"question": "Sixth move in solving 3-disk Tower of Hanoi?", "options": ["Medium to Right", "Small to Middle", "Big to Middle", "Small to Right"], "correct": "Medium to Right", "points": 2},
        ]
    },
    {
        "id": 24,
        "name": "Shopping List Memory → Grocery Run",
        "description": "Remember the shopping list: Milk, Bread, Eggs - test working memory",
        "questions": [
            {"question": "Shopping list: Milk, Bread, Eggs. What was the FIRST item?", "options": ["Milk", "Bread", "Eggs", "Butter"], "correct": "Milk", "points": 2},
            {"question": "Shopping list: Milk, Bread, Eggs. What was the SECOND item?", "options": ["Milk", "Bread", "Eggs", "Butter"], "correct": "Bread", "points": 2},
            {"question": "Shopping list: Milk, Bread, Eggs. What was the THIRD item?", "options": ["Milk", "Bread", "Eggs", "Butter"], "correct": "Eggs", "points": 2},
            {"question": "Was Butter on the list?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Was Milk on the list?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Was Bread on the list?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Was Cheese on the list?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Name items 1 and 2.", "options": ["Milk, Bread", "Bread, Eggs", "Milk, Eggs", "Bread, Milk"], "correct": "Milk, Bread", "points": 2},
            {"question": "Name items 2 and 3.", "options": ["Milk, Bread", "Bread, Eggs", "Milk, Eggs", "Eggs, Bread"], "correct": "Bread, Eggs", "points": 2},
            {"question": "Name all 3 items in order.", "options": ["Milk, Bread, Eggs", "Bread, Milk, Eggs", "Eggs, Bread, Milk", "Milk, Eggs, Bread"], "correct": "Milk, Bread, Eggs", "points": 2},
            {"question": "Which item came after Milk?", "options": ["Bread", "Eggs", "Butter", "Cheese"], "correct": "Bread", "points": 2},
            {"question": "Which item came before Eggs?", "options": ["Bread", "Milk", "Butter", "Cheese"], "correct": "Bread", "points": 2},
            {"question": "Was Juice on the list?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Was Eggs on the list?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "What was the last item on the list?", "options": ["Milk", "Bread", "Eggs", "Butter"], "correct": "Eggs", "points": 2},
        ]
    },
    {
        "id": 25,
        "name": "Fidget Tracker → Sitting Still Challenge",
        "description": "Answer if you stayed still - test motor activity and fidgeting",
        "questions": [
            {"question": "You wiggled your fingers. Did you stay still?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You sat with still hands. Did you stay still?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You tapped your foot. Did you stay still?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You kept both feet on floor. Did you stay still?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You touched your hair. Did you stay still?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You sat like a statue. Did you stay still?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You moved your shoulders. Did you stay still?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You kept hands on lap. Did you stay still?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You looked around but didn't move body. Did you stay still?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You swung your legs. Did you stay still?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You kept back straight. Did you stay still?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You touched your face. Did you stay still?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You sat without fidgeting for 10 seconds. Did you stay still?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You bounced on your seat. Did you stay still?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You stayed completely still for 5 seconds. Did you stay still?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 26,
        "name": "Stay in Your Seat Challenge → Seat Keeper",
        "description": "Answer if you stayed in your seat - test restlessness",
        "questions": [
            {"question": "You stood up. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You stayed sitting. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You knelt on your seat. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You walked around. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You sat properly. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You turned around but bottom stayed on seat. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You got up to get a pencil. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You sat the whole time. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You leaned way back but seat still touched. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You left to talk to a friend. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You sat with legs crossed on chair. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You stood up and sat down again. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "You sat like a teacher. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You tried to leave but stopped. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "You never left your seat. Did you stay in your seat?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 27,
        "name": "Drawing Copy Challenge → Copy the Picture",
        "description": "Compare copy to original - test fine motor control",
        "questions": [
            {"question": "Circle drawn as a circle. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Square has 4 corners. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Triangle has 3 sides. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Line is straight. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Circle looks like a blob. Was the copy accurate?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Square has round edges. Was the copy accurate?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Triangle has 4 sides. Was the copy accurate?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Circle size is similar to original. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Lines connect at corners. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Drawing is messy. Was the copy accurate?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Circle is complete (closed shape). Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Square has overlapping lines. Was the copy accurate?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Triangle is pointy. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Copy matches original overall. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Child stayed inside the lines. Was the copy accurate?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 28,
        "name": "Frustration Induction Puzzle → Never Give Up",
        "description": "Answer after solving a hard puzzle - test persistence",
        "questions": [
            {"question": "Did you try again after making a mistake?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you shout or give up when it got hard?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Did you ask for help when you needed it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you keep trying for at least 1 minute?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you blame the game for being too hard?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Did you restart the puzzle to try again?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you try a different strategy when one didn't work?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you say 'I can't' and stop trying?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Did you take a deep breath and continue?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you try at least 3 times to solve it?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you get frustrated but keep going anyway?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you slam the table or throw anything?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Did you look for a new solution when stuck?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you eventually finish the puzzle?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Did you learn something from the hard part?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
        ]
    },
    {
        "id": 29,
        "name": "Shape Sorter → Match the Shape",
        "description": "Match shapes to correct holes - test spatial reasoning",
        "questions": [
            {"question": "Circle goes into which hole?", "options": ["Circle hole", "Square hole", "Triangle hole", "Star hole"], "correct": "Circle hole", "points": 2},
            {"question": "Square goes into which hole?", "options": ["Circle hole", "Square hole", "Triangle hole", "Star hole"], "correct": "Square hole", "points": 2},
            {"question": "Triangle goes into which hole?", "options": ["Circle hole", "Square hole", "Triangle hole", "Star hole"], "correct": "Triangle hole", "points": 2},
            {"question": "Star goes into which hole?", "options": ["Circle hole", "Square hole", "Triangle hole", "Star hole"], "correct": "Star hole", "points": 2},
            {"question": "Heart goes into which hole?", "options": ["Circle hole", "Square hole", "Triangle hole", "Heart hole"], "correct": "Heart hole", "points": 2},
            {"question": "Does a circle fit into a square hole?", "options": ["Yes", "No"], "correct": "No", "points": 2},
            {"question": "Does a small square fit into a big square hole?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "Turn a triangle upside down. Is it still a triangle?", "options": ["Yes", "No"], "correct": "Yes", "points": 2},
            {"question": "A rotated square is still a...", "options": ["Square", "Circle", "Triangle", "Rectangle"], "correct": "Square", "points": 2},
            {"question": "Which shape has 3 corners?", "options": ["Circle", "Square", "Triangle", "Star"], "correct": "Triangle", "points": 2},
            {"question": "Which shape has 4 equal sides?", "options": ["Circle", "Square", "Triangle", "Rectangle"], "correct": "Square", "points": 2},
            {"question": "Which shape has no corners?", "options": ["Circle", "Square", "Triangle", "Star"], "correct": "Circle", "points": 2},
            {"question": "Which shape fits best into a circle hole?", "options": ["Circle", "Square", "Triangle", "Star"], "correct": "Circle", "points": 2},
            {"question": "Can a rectangle fit into a square hole?", "options": ["Only if smaller", "Yes always", "No never", "Only if larger"], "correct": "Only if smaller", "points": 2},
            {"question": "Match shape to hole: Star", "options": ["Circle hole", "Square hole", "Triangle hole", "Star hole"], "correct": "Star hole", "points": 2},
        ]
    }
]

def get_all_games():
    """Return complete list of 29 games"""
    return GAMES_DATA

def get_game_by_id(game_id):
    """Get a specific game by ID"""
    for game in GAMES_DATA:
        if game['id'] == game_id:
            return game
    return None

def get_total_games():
    """Return total number of games"""
    return len(GAMES_DATA)

def get_game_names():
    """Return list of all game names"""
    return [game['name'] for game in GAMES_DATA]